### ISSUE TITLE
Adding description and title to extension

### ISSUE THREAD

**Issue by jwtiyar** [silnrsi/oxttools#9]
Hey
Thanks for great tool.
But How I can add a description to my extension? Or something like adding credits, And a README file.

Best regards.

**Comment by DavidLRowe** [comment]
There is currently no way to do this directly, though we would be interested in what you propose adding.

As a workaround, you could take the .oxt file that this tool creates, unzip it, edit existing files or add new ones, then zip it up again. (You might have to rename xyz.oxt to xyz.zip to make the file recognisable to the unzip process.) Any new files you add would need to conform to LibreOffice's .oxt format.

**Comment by DavidLRowe** [comment]
Closing this for the present. Feel free to reopen it (or open a new issue) with a concrete proposal included.

Thanks for your interest!
